LICENSE
README.md

feat: update name

---

README.md

I tried to improve the readme to make it easier to remember, but maybe I used too many emoticons. Let me know what you think and we can iterate.

chore: update readme design

---

MAINTAINERS

Add Julián Campana to MAINTAINERS list.

docs: update MAINTAINERS

---

.github/workflows/comment_artifact_url_on_pr.yml
.github/workflows/flutter_build_apk.yml

Resolves #27 
Automatically build APK in each new PR

feat: automatic APK build

---

.aider-current-task.md
DESIGN.md
STYLE-GUIDE.md
app/lib/customers_page.dart
app/lib/new_customer_page.dart

Resolves #18 
Same as #29, but for the new customer page

feat: basic new customer page

---

app/lib/data_exporter.dart
app/lib/database_helper.dart
app/lib/settings_page.dart

Resolves #21
- The data export feature will copy a version of the user's DB to the Android Downloads folder

feat: data export

---

app/pubspec.yaml

Oops I forgot to bump the version number when I created the tag 🤦🏽

release: v0.2.0

---

app/lib/database_helper.dart
app/lib/edit_environmental_conditions_page.dart
app/lib/record.dart
app/lib/records_dao.dart
app/lib/records_page.dart

Related to #49 
- Added new fields to the `Record` class for environmental conditions
- Added a new page for editing these fields
- Include values in the generated PDF

feat: environmental conditions

---

app/lib/pdf_generator.dart

Fixed a permission error I was getting with the PDF generation logic.

fix: use Download directory for PDFs

---

app/lib/applicators_page.dart
app/lib/main.dart
app/lib/settings_page.dart
app/lib/top_level_page.dart

Related to #43 
- Moved Applicators from the nav bar to the settings page

feat: move applicators to settings

---

app/lib/records_page.dart
app/pubspec.yaml

- Added "Coming Soon" dialog for the pesticides option
- Bumped version number

release: v0.3.0

---

meetings/2025/03-22/notes.md

notes: 2025-03-22

---

app/pubspec.yaml

- Removed unit conversion from code base.

release: v0.3.1

---

app/lib/database_helper.dart
app/lib/pesticide/edit_pesticide_page.dart
app/lib/pesticide/pesticide.dart
app/lib/pesticide/pesticide_dao.dart
app/lib/pesticide/pesticides_page.dart
app/lib/settings_page.dart

- Added `pesticide` and `record_pesticide` tables.
- Added Pesticides and Edit Pesticides pages.
- Test adding new pesticides.
- Test editing pesticides.

feat: add pesticides

---

app/lib/pdf_generator.dart

Resolves #83 #81
Improved PDF generation logic
- Correctly fetch customer
- Remove dangerous characters from paths
- Removed logic to delete old file - it was causing errors on my system for some files

fix: PDF generation

---

app/lib/database_helper.dart
app/lib/edit_record_page.dart
app/lib/pdf_generator.dart
app/lib/record.dart
app/lib/records_dao.dart

Resolved #66, #67, #68, #69, and #70
- Added `crop` field #66 
- Added `totalArea` field #67 
- Added `pricePerAcre` field #68 
- Added `sprayVolume` field #69 
- Added `notes` field #70

feat: add more settings

---

app/lib/database_helper.dart
app/lib/edit_record_page.dart
app/lib/pdf_generator.dart
app/lib/record.dart
app/lib/records_dao.dart
app/lib/records_page.dart

This one should be merged after #86, I branched of that branch.
Resolves #82 
- Renamed `timestamp` column to `start_imestamp`
- Added `end_timestamp` column
- Allow the user to edit the date and times
- Improve date format in PDF
- Add the times to the PDF
- Don't allow 0 for total acres, price per acre, or spray volume

feat: improve date

---

app/pubspec.yaml

release: v0.4.0

---

meetings/2025/03-29/notes.md

notes: 03-29 meeting

---

_redirects

Related to #92 
- Removed the redirect so we can run the web app directly on karriba.com

feat: remove redirect

---

app/lib/data_exporter.dart
app/lib/data_importer.dart
app/lib/database_helper.dart
app/lib/pdf_generator.dart

Related to #92 
- Export to JSON
- Support importing from JSON
- On Android, we still support importing from DB files. In the future we will remove this.
- Export your data as a JSON on your Android device
- Import the JSON data in the web app

feat: import from JSON

---

app/pubspec.yaml

release: v0.5.0
